"""
Django settings for pathfinder project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*1&qb26(-v6(0sj7ktc&rt%gmq6*0w!=p(-uq&5f1lk27v@2wq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

PATHFINDER_HOST_ADDRESS = os.environ.get('PATHFINDER_HOST_ADDRESS', '127.0.0.1')

ALLOWED_HOSTS = [PATHFINDER_HOST_ADDRESS, 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'route_collector',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pathfinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pathfinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

PATHFINDER_DB_NAME = os.environ.get('PATHFINDER_DB_NAME', 'pathfinder')
PATHFINDER_DB_USER_NAME = os.environ.get('PATHFINDER_DB_USER_NAME', 'pathfinder')
PATHFINDER_DB_PASSWORD = os.environ.get('PATHFINDER_DB_PASSWORD', 'pathfinder')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': PATHFINDER_DB_NAME,
        'USER': PATHFINDER_DB_USER_NAME,
        'PASSWORD': PATHFINDER_DB_PASSWORD,
        'HOST': PATHFINDER_HOST_ADDRESS,
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ]
}

CORS_ORIGIN_ALLOW_ALL = True

RMQ_HOST = os.environ.get('RMQ_HOST', 'amqp://guest:guest@127.0.0.1:5672')
RMQ_ROUTE_CREATOR_EXCHANGE = os.environ.get('RMQ_ROUTE_CREATOR_EXCHANGE', 'rmq_route_creator_exchange')
RMQ_ROUTE_CREATOR_QUEUE_IN = os.environ.get('RMQ_ROUTE_CREATOR_QUEUE_IN', 'rmq_route_creator_queue_in')
